FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY NiceGUI_frontend/requirements.txt ./NiceGUI_frontend/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r NiceGUI_frontend/requirements.txt

COPY NiceGUI_frontend ./NiceGUI_frontend

EXPOSE 8501

CMD ["python", "NiceGUI_frontend/main.py"]